 
name: dexternoobclang15.x

on:
  push:
  schedule:
    - cron: '0 6 * * *'

env:
    GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
    TELEGRAM_CHAT: ${{ secrets.TELEGRAM_CHAT }}
    TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
  
jobs:
  goBuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Building
      run: |
        
        bash build-ci.sh release/15.x
