name: Clang build

on:
  schedule:
    - cron: '0 0 * * 0,4'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        branch: [main]

    env:
      BRANCH: ${{ matrix.branch }}
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      TELEGRAM_CHAT: ${{ secrets.TELEGRAM_CHAT }}
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - name: build ${{ matrix.branch }} branch
        run: |
          git clone -b main https://github.com/DexterNoob/clang-build
          cd clang-build || exit
          bash ci.sh deps
          bash build.sh
